version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_SECRET=subs-manager-prod-secret-2026
      - NEXTAUTH_URL=http://localhost:3000
    restart: always
