import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        monai: {
          bg: "var(--bg-app)",
          sheet: "var(--bg-sheet)",
          surface: "var(--surface)",
          elevated: "var(--surface-elevated)",
          tag: "var(--tag)",
          border: "var(--border)",
          subtle: "var(--border-subtle)",
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          placeholder: "var(--text-placeholder)",
          green: "var(--green)",
          coral: "var(--coral)",
          amber: "var(--amber)",
          "amber-soft": "var(--amber-soft)",
          "pill-light": "var(--pill-light)",
          "pill-light-text": "var(--pill-light-text)",
        },
        apple: {
          bg: "var(--bg-app)",
          card: "var(--surface)",
          text: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-placeholder)",
          border: "var(--border)",
          accent: "var(--coral)",
          "accent-soft": "rgba(232, 80, 91, 0.12)",
          "accent-hover": "#D73F4A",
          success: "var(--green)",
          "success-soft": "rgba(52, 199, 89, 0.15)",
          warning: "var(--amber)",
          "warning-soft": "var(--amber-soft)",
          danger: "var(--coral)",
          "danger-soft": "rgba(232, 80, 91, 0.15)",
          purple: "#8B5CF6",
          "purple-soft": "#F3E8FF",
        },
      },
      fontFamily: {
        sans: [
          "Nunito",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        nunito: ["Nunito", "sans-serif"],
      },
      fontSize: {
        giant: ["68px", { lineHeight: "1", letterSpacing: "-0.03em", fontWeight: "900" }],
        "sheet-title": ["32px", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "900" }],
        row: ["17px", { lineHeight: "1.3", fontWeight: "800" }],
        sub: ["14px", { lineHeight: "1.4", fontWeight: "600" }],
        tag: ["13px", { lineHeight: "1.4", fontWeight: "700" }],
      },
      borderRadius: {
        pill: "999px",
        bar: "24px",
        sheet: "32px 32px 0 0",
        "sheet-all": "32px",
        squircle: "22%",
        card: "20px",
        input: "16px",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
      },
      boxShadow: {
        apple: "0 4px 20px -2px rgba(0, 0, 0, 0.25)",
        "apple-hover": "0 8px 30px -4px rgba(0, 0, 0, 0.35)",
        "apple-modal": "0 24px 60px -10px rgba(0, 0, 0, 0.5)",
      },
    },
  },
  plugins: [],
};

export default config;
